world(tests): simplify lint, deadnix and dscheck

diff --git a/files/Justfile b/files/Justfile
--- a/files/Justfile
+++ b/files/Justfile
@@ -94,18 +94,33 @@ gh-release-update:
 
 [private]
 lint:
-  @echo '-------- [Linting] ---------'
-  @let out = (statix check . | complete); if ($out.exit_code > 0) { let span = (metadata $out).span; error make {msg: "Linting failed", label: {text: $out.stdout, span: $span}} } else { print "Lint ok\n\n"; print $out.stdout }
+  #!/usr/bin/env bash
+  echo '-------- [Linting] ---------'
+  if ! statix check .; then
+    echo "Linting failed"
+    exit 1
+  fi
+  echo "Lint ok"
 
 [private]
 dead:
-  @echo '-------- [Check for dead code] ---------'
-  @let out = (deadnix -f . | complete); if ($out.exit_code > 0) { let span = (metadata $out).span; error make {msg: "Dead code check failed", label: {text: $out.stdout, span: $span}} } else { print "No dead code\n\n"; print $out.stdout }
+  #!/usr/bin/env bash
+  echo '-------- [Check for dead code] ---------'
+  if ! deadnix -f .; then
+    echo "Dead code check failed"
+    exit 1
+  fi
+  echo "No dead code"
 
 [private]
 dscheck:
-  @echo '-------- [Flake checker] ---------'
-  @let out = (nix run github:DeterminateSystems/flake-checker | complete); if ($out.exit_code > 0) { let span = (metadata $out).span; error make {msg: "Flake checker failed", label: {text: $out.stdout, span: $span}} } else { print "Flake is good\n\n"; print $out.stdout }
+  #!/usr/bin/env bash
+  echo '-------- [Flake checker] ---------'
+  if ! nix run github:DeterminateSystems/flake-checker; then
+    echo "Flake checker failed"
+    exit 1
+  fi
+  echo "Flake is good"
 
 [private]
 check:
